"""
test_persistencia_modelos.py
=============================
Cubre app/ia/persistencia_modelos.py: cuando xgboost avisa que un
modelo fue serializado con una versión distinta a la instalada, el
modelo debe re-guardarse una sola vez para que esa máquina no vuelva
a ver el aviso en cargas futuras.
"""

import time
import warnings
from pathlib import Path

import joblib
import pytest

from app.ia.persistencia_modelos import cargar_xgboost_con_auto_migracion


class _ModeloDeMentira:
    """Sustituto liviano de ModeloXGBoost/ModeloXGBoostMerma: no hace
    falta un XGBRegressor real para probar la lógica de re-guardado,
    solo algo que joblib pueda serializar."""
    valor = 42


def _simular_aviso_de_version(monkeypatch, texto_aviso):
    original_load = joblib.load

    def load_con_aviso(*args, **kwargs):
        warnings.warn(texto_aviso, UserWarning)
        return original_load(*args, **kwargs)

    monkeypatch.setattr(joblib, "load", load_con_aviso)


def test_no_reguarda_si_no_hay_aviso_de_version(tmp_path):
    ruta = tmp_path / "modelo.pkl"
    joblib.dump(_ModeloDeMentira(), ruta)
    mtime_antes = ruta.stat().st_mtime

    modelo = cargar_xgboost_con_auto_migracion(ruta)

    assert modelo.valor == 42
    assert ruta.stat().st_mtime == mtime_antes  # no se tocó el archivo


def test_reguarda_una_vez_cuando_xgboost_avisa_version_distinta(monkeypatch, tmp_path):
    ruta = tmp_path / "modelo.pkl"
    joblib.dump(_ModeloDeMentira(), ruta)
    mtime_antes = ruta.stat().st_mtime

    original_load = joblib.load
    _simular_aviso_de_version(
        monkeypatch,
        "If you are loading a serialized model (like pickle in Python, RDS in R) or "
        "configuration generated by an older version of XGBoost, please export the "
        "model by calling `Booster.save_model` from that version first.",
    )
    time.sleep(0.01)  # asegura que el mtime del re-guardado sea distinguible

    modelo = cargar_xgboost_con_auto_migracion(ruta)

    assert modelo.valor == 42
    assert ruta.stat().st_mtime != mtime_antes  # se re-guardó

    # Segunda carga, ya SIN el aviso simulado (el archivo real ya
    # quedaría en el formato de la versión actual, así que xgboost no
    # volvería a avisar): no debería re-guardar de nuevo.
    monkeypatch.setattr(joblib, "load", original_load)
    mtime_tras_migracion = ruta.stat().st_mtime
    modelo_2 = cargar_xgboost_con_auto_migracion(ruta)
    assert modelo_2.valor == 42
    assert ruta.stat().st_mtime == mtime_tras_migracion


def test_ignora_advertencias_no_relacionadas_con_version(monkeypatch, tmp_path):
    """Otro UserWarning cualquiera (no el de versión de xgboost) no
    debe disparar un re-guardado innecesario."""
    ruta = tmp_path / "modelo.pkl"
    joblib.dump(_ModeloDeMentira(), ruta)
    mtime_antes = ruta.stat().st_mtime

    _simular_aviso_de_version(monkeypatch, "Esto es un aviso totalmente distinto, sin relación.")

    modelo = cargar_xgboost_con_auto_migracion(ruta)

    assert modelo.valor == 42
    assert ruta.stat().st_mtime == mtime_antes


def test_no_falla_si_no_se_puede_reguardar(monkeypatch, tmp_path):
    """Si el re-guardado falla (permisos, disco de solo lectura, etc.)
    el modelo ya cargado en memoria se sigue devolviendo igual —
    perder la oportunidad de dejar de ver el aviso no debe romper la
    predicción de esta sesión."""
    ruta = tmp_path / "modelo.pkl"
    joblib.dump(_ModeloDeMentira(), ruta)

    _simular_aviso_de_version(
        monkeypatch,
        "... generated by an older version of XGBoost, please export the model ...",
    )

    def dump_que_falla(*args, **kwargs):
        raise OSError("disco de solo lectura (simulado)")

    monkeypatch.setattr(joblib, "dump", dump_que_falla)

    modelo = cargar_xgboost_con_auto_migracion(ruta)
    assert modelo.valor == 42
